name: CI

on: [push]

jobs:
  deploy:
    if: github.ref === 'ref/heads/main'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          command_timeout: 200m
          script:
            cd /home/www/todolist/project/todolist
            git pull
            cd ../
            docker compose dowm
            docker compose up -d
            docker exec -it --user www-data php bash -c "cd /var/www && composer install"
