name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          command_timeout: 200m
          script:
            cd ~/www/todolist/project/todolist &&
            git pull &&
            cd ../ && 
            docker compose dowm && 
            docker compose up -d &&
            docker exec -it --user www-data php bash -c "cd /var/www && composer install"
